Ed-Fi-Exchange-OSS/API-to-AMT-Data-Lake

src/edfi_amt_data_lake/api/api.py, src/edfi_amt_data_lake/helper/helper.py
- Add call to deletes endpoint.
- Update save file function to fix a bug: if the destination folder exists, the function doesn't create the file for the new version.
- Update to avoid saving empty json files.
Filename pattern: <endpointname>_deletes_<version>.json
=> [BIA-1166] Implement change queries from API - Deletes

src/edfi_amt_data_lake/api/api.py, src/edfi_amt_data_lake/api/changeVersion.py, src/edfi_amt_data_lake/helper/helper.py, src/edfi_amt_data_lake/parquet/Common/functions.py, src/edfi_amt_data_lake/parquet/Common/pandasWrapper.py, src/edfi_amt_data_lake/parquet/amt/asmt/AssessmentFact/script.py, src/edfi_amt_data_lake/parquet/amt/base/SchoolDim/script.py, src/edfi_amt_data_lake/parquet/amt/ews/StudentEarlyWarningFactDim/script.py, src/edfi_amt_data_lake/parquet/amt/ews/StudentSectionGradeFact/script.py, src/edfi_amt_data_lake/parquet/amt_parquet.py
- Add school_year parameter to save parquet function. 
- Update save_parquet and toCsv functions.
- Update API to Parquet functions to include de school_year parameter. 
- Update functions to create destination folder if not exists.
=> [BIA-1215] Add SchoolYear Parameter to SaveParquet function

src/edfi_amt_data_lake/parquet/amt/equity/StudentSchoolFoodServiceProgramDim/script.py, src/edfi_amt_data_lake/parquet/amt/equity/equity_collection.py, src/edfi_amt_data_lake/parquet/amt/equity/feeder_school_dim/__init__.py, src/edfi_amt_data_lake/parquet/amt/equity/feeder_school_dim/main.py
Inserts to test
```
INSERT INTO edfi.FeederSchoolAssociation VALUES ('2010-01-01',255901044,255901001,NULL,'Feeder School1',NULL,GETDATE(),GETDATE(),NEWID(),1)
INSERT INTO edfi.FeederSchoolAssociation VALUES ('2010-01-01',255901107,255901044,NULL,'Feeder School2',NULL,GETDATE(),GETDATE(),NEWID(),1)
INSERT INTO edfi.FeederSchoolAssociation VALUES ('2010-01-01',5,255901107,NULL,'Feeder School3',NULL,GETDATE(),GETDATE(),NEWID(),1)
INSERT INTO edfi.FeederSchoolAssociation VALUES ('2010-01-01',255901001,255901044,NULL,'Feeder School4',NULL,GETDATE(),GETDATE(),NEWID(),1)
```
=> [BIA-1172] Add FeederSchoolDim script.

src/edfi_amt_data_lake/parquet/Common/pandasWrapper.py, src/edfi_amt_data_lake/parquet/amt/base/date_dim/__init__.py, src/edfi_amt_data_lake/parquet/amt/base/date_dim/main.py
=> [BIA-1195] Implement API to AMT parquet conversion -DateDim

src/edfi_amt_data_lake/helper/endpoint/endpoint.json, src/edfi_amt_data_lake/parquet/Common/functions.py, src/edfi_amt_data_lake/parquet/Common/pandasWrapper.py, src/edfi_amt_data_lake/parquet/amt/equity/equity_collection.py, src/edfi_amt_data_lake/parquet/amt/equity/student_program_cohort_dim/__init__.py, src/edfi_amt_data_lake/parquet/amt/equity/student_program_cohort_dim/main.py
Add studentProgramCohortDim view.
Add function to get descriptor code value by uri.
Add function get reference id by href.
=> [BIA-1174] Implement API to AMT parquet conversion StudentProgramCohortDim

src/dagster_data_lake/dagster_data_lake/jobs/pipe_api.py, src/dagster_data_lake/dagster_data_lake/ops/api.py, src/edfi_amt_data_lake/parquet/amt/epp/candidate_survey_dim/__init__.py, src/edfi_amt_data_lake/parquet/amt/epp/candidate_survey_dim/main.py, src/edfi_amt_data_lake/parquet/amt/epp/epp_collection.py
- Update workflow to have to steps: get_api_data and generate_parquet.
- Add candidate_survey_dim.
=> [BIA-1197] Implement API to AMT - epp_CandidateSurveyDim

src/dagster_data_lake/dagster_data_lake/ops/api.py, src/edfi_amt_data_lake/parquet/Common/descriptor_mapping.py, src/edfi_amt_data_lake/parquet/Common/pandasWrapper.py, src/edfi_amt_data_lake/parquet/amt/rls/rls_collection.py, src/edfi_amt_data_lake/parquet/amt/rls/rls_student_data_authorization/__init__.py, src/edfi_amt_data_lake/parquet/amt/rls/rls_student_data_authorization/main.py
Create studentDataAuthorization view.
=> [BIA-1157] Implement API to AMT parquet conversion - rls_StudentDataAuthorization

src/edfi_amt_data_lake/parquet/Common/pandasWrapper.py, src/edfi_amt_data_lake/parquet/amt/base/base_collection.py, src/edfi_amt_data_lake/parquet/amt/base/local_education_agency_dim/__init__.py, src/edfi_amt_data_lake/parquet/amt/base/local_education_agency_dim/main.py
* Add scripts to create the LocalEducationAgencyDim view.
=> [BIA-1178] API to AMT parquet conversion - core collection - LocalEducationAgencyDim

src/edfi_amt_data_lake/parquet/Common/pandasWrapper.py, src/edfi_amt_data_lake/parquet/amt/rls/rls_collection.py, src/edfi_amt_data_lake/parquet/amt/rls/rls_user_student_data_authorization/__init__.py, src/edfi_amt_data_lake/parquet/amt/rls/rls_user_student_data_authorization/main.py
Add scripts to create the view.
=> [BIA-1206] API to AMT - RLS_userDataAuthorization 

src/edfi_amt_data_lake/helper/endpoint/endpoint.json, src/edfi_amt_data_lake/parquet/amt/epp/epp_collection.py, src/edfi_amt_data_lake/parquet/amt/epp/epp_financial_aid_fact/__init__.py, src/edfi_amt_data_lake/parquet/amt/epp/epp_financial_aid_fact/main.py, src/edfi_amt_data_lake/parquet/amt/epp/evaluation_element_rating_dim/main.py
Add aidTypeDescriptors endpoint.
Add fact view.
=> [BIA-1198] Implement API to AMT parquet conversion - EPP - EPP_FinancialAidFact

src/edfi_amt_data_lake/parquet/amt/base/base_collection.py, src/edfi_amt_data_lake/parquet/amt/base/student_program_dim/__init__.py, src/edfi_amt_data_lake/parquet/amt/base/student_program_dim/main.py, src/edfi_amt_data_lake/parquet/amt_parquet.py
- Implement API to AMT parquet conversion - core collection - StudentProgramDim
=> BIA-1185: Implement API to AMT parquet conversion - core collection - StudentProgramDim

src/edfi_amt_data_lake/parquet/Common/pandasWrapper.py, src/edfi_amt_data_lake/parquet/amt/base/base_collection.py, src/edfi_amt_data_lake/parquet/amt/base/demographics_dim/__init__.py, src/edfi_amt_data_lake/parquet/amt/base/demographics_dim/main.py, src/edfi_amt_data_lake/parquet/amt/base/school_dim/main.py, src/edfi_amt_data_lake/parquet/amt/epp/candidate_dim/main.py, src/edfi_amt_data_lake/parquet/amt/equity/student_program_cohort_dim/main.py, src/edfi_amt_data_lake/parquet/amt/rls/rls_user_dim/main.py
Add DemographicDim view script.
=> [BIA-1179] Implement API to AMT - Core DemographicDim

src/pyproject.toml
=> [BIA-1256] Set PSUtils version to 5.9.3

src/edfi_amt_data_lake/helper/data_frame_generation_result.py, src/edfi_amt_data_lake/parquet/Common/descriptor_mapping.py, src/edfi_amt_data_lake/parquet/Common/pandasWrapper.py, src/edfi_amt_data_lake/parquet/amt/base/school_dim/main.py
- Add columns names for meta and result_meta.
- Add condition to return empty if a merge retorn none. 
- Add a class to return dataframe generation result. 
- Update pandasWrapper to fix bugs.
=> [BIA-1233] SchoolDim: consider optional data.

src/edfi_amt_data_lake/parquet/amt/base/base_collection.py, src/edfi_amt_data_lake/parquet/amt/base/student_section_dim/main.py
Add scripts to create StudentSectionDim
=> [BIA-1188] API to AMT parquet  - core collection - StudentSectionDim

src/edfi_amt_data_lake/parquet/Common/pandasWrapper.py, src/edfi_amt_data_lake/parquet/amt/base/base_collection.py, src/edfi_amt_data_lake/parquet/amt/base/student_local_education_agency_demographics_bridge/main.py, src/edfi_amt_data_lake/parquet/amt/base/student_school_demographics_bridge/__init__.py, src/edfi_amt_data_lake/parquet/amt/base/student_school_demographics_bridge/main.py
Add script to create StudentSchoolDemographicsBridge.
=> [BIA-1181] Implement API to AMT parquet conversion -StudentSchoolDemographicsBridge

src/edfi_amt_data_lake/parquet/Common/pandasWrapper.py, src/edfi_amt_data_lake/parquet/amt/base/base_collection.py, src/edfi_amt_data_lake/parquet/amt/base/class_period_dim/main.py, src/edfi_amt_data_lake/parquet/amt/base/student_local_education_agency_dim/__init__.py, src/edfi_amt_data_lake/parquet/amt/base/student_local_education_agency_dim/main.py
Add scripts to create StudentLocalEducationAgencyDim
=> [BIA-1186] Implement API to AMT parquet conversion - StudentLocalEducationAgencyDim

src/edfi_amt_data_lake/parquet/amt/base/academic_time_period_dim/__init__.py, src/edfi_amt_data_lake/parquet/amt/base/academic_time_period_dim/main.py, src/edfi_amt_data_lake/parquet/amt/base/base_collection.py
- Implement API to AMT parquet conversion - core collection - AcademicTimePeriodDim
=> [BIA-1190]: Implement API to AMT parquet conversion - core collection - AcademicTimePeriodDim

src/edfi_amt_data_lake/parquet/amt/base/date_dim/main.py
=> [BIA-1279] Consider optional data - DateDim

src/edfi_amt_data_lake/parquet/amt/base/local_education_agency_dim/main.py
Add optional fields validation.
=> [BIA-1281] Consider optional data - LocalEducationAgencyDim

src/edfi_amt_data_lake/parquet/amt/base/demographics_dim/main.py
=> [BIA-1282] Consider optional data - DemographicDim

src/edfi_amt_data_lake/helper/endpoint/endpoint.json, src/edfi_amt_data_lake/parquet/amt/asmt/assessment_fact/main.py
- Add resultDatatypeTypeDescriptors endpoint
- Validate optional data.
- Update AssessmentFactKey to use descriptorId.
=> [BIA-1258] Consider optional data - AssessmentFact

src/edfi_amt_data_lake/parquet/Common/descriptor_mapping.py, src/edfi_amt_data_lake/parquet/amt/rls/rls_user_student_data_authorization/main.py
Update script to add decorator and validations.
Fix descriptorMapping script
=> [BIA-1276] Optional data: rls_UserStudentDataAuthorization

setup.cfg, src/.flake8, src/mypy.ini
=> [BIA-1294]: API-to-AMT stop ignoring mypy errors

src/.flake8, src/dagster_data_lake/dagster_data_lake/__init__.py, src/dagster_data_lake/dagster_data_lake/ops/api.py, src/dagster_data_lake/dagster_data_lake/repository.py, src/dagster_data_lake/dagster_data_lake/schedules/schedule.py, src/dagster_data_lake/dagster_data_lake/sensors/sensor.py, src/dagster_data_lake/dagster_data_lake_tests/test_graphs/test_pipe_api.py, src/dagster_data_lake/dagster_data_lake_tests/test_ops/test_api.py, src/edfi_amt_data_lake/api/api.py, src/edfi_amt_data_lake/helper/helper.py, src/edfi_amt_data_lake/helper/token.py, src/edfi_amt_data_lake/parquet/Common/descriptor_mapping.py, src/edfi_amt_data_lake/parquet/Common/pandasWrapper.py, src/edfi_amt_data_lake/parquet/amt/asmt/student_assessment_fact/main.py, src/edfi_amt_data_lake/parquet/amt/base/student_school_demographics_bridge/main.py, src/edfi_amt_data_lake/parquet/amt/rls/rls_user_student_data_authorization/main.py, src/mypy.ini, src/poetry.lock, src/pyproject.toml
- Fix dependency compilation missed
=> [BIA-1300]: Fix dependency compilation missed

README.md, src/edfi_amt_data_lake/parquet/Common/pandasWrapper.py, src/edfi_amt_data_lake/parquet/amt/ews/student_early_warning_fact/main.py
Add script
Add validation to add empty columns.
=> [BIA-1259] Consider optional data - StudentEarlyWarningFact

src/dagster_data_lake/dagster_data_lake/__init__.py, src/edfi_amt_data_lake/helper/helper.py, src/edfi_amt_data_lake/parquet/Common/descriptor_mapping.py, src/edfi_amt_data_lake/parquet/Common/pandasWrapper.py, src/edfi_amt_data_lake/parquet/amt/base/all_student_school_dim/main.py, src/edfi_amt_data_lake/parquet/amt/base/student_school_dim/main.py, src/edfi_amt_data_lake/parquet/amt/chrab/chronic_absenteeism_attendance_fact/main.py, src/edfi_amt_data_lake/parquet/amt/equity/equity_collection.py, src/edfi_amt_data_lake/parquet/amt/equity/student_history_dim/__init__.py, src/edfi_amt_data_lake/parquet/amt/equity/student_history_dim/main.py
Add student_history_dim script.
=> [BIA-1175] Implement API to AMT parquet conversion - StudentHistoryDim

src/dagster_data_lake/dagster_data_lake/ops/api.py
- Handle parquet creation scripts errors
=> [BIA-1231]: Handle parquet creation scripts errors

src/edfi_amt_data_lake/parquet/amt/asmt/assessment_fact/main.py, src/edfi_amt_data_lake/parquet/amt/asmt/student_assessment_fact/main.py
Update Student Assessment Script
=> [BIA-1298] Consider optional data - StudentAssessmentFact

src/edfi_amt_data_lake/parquet/amt/asmt/student_assessment_fact/main.py, src/edfi_amt_data_lake/parquet/amt/epp/candidate_survey_dim/main.py
- Consider optional data - epp_CandidateSurveyDim
=> [BIA-1266]: Consider optional data - epp_CandidateSurveyDim

src/edfi_amt_data_lake/parquet/amt/epp/epp_financial_aid_fact/main.py
- Consider optional data - EPP_FinancialAidFact
=> [BIA-1268] Consider optional data - EPP_FinancialAidFact

src/edfi_amt_data_lake/parquet/amt/asmt/student_assessment_fact/main.py
- Improve Parquet Files - Assessment Collection
=> [BIA-1303] Improve Parquet Files - Assessment Collection

src/edfi_amt_data_lake/parquet/amt/chrab/chronic_absenteeism_attendance_fact/main.py
-  Improve Parquet Files - Chrab Collection
=> [BIA-1305] Improve Parquet Files - Chrab Collection

src/edfi_amt_data_lake/parquet/amt/equity/student_discipline_action_dim/main.py, src/edfi_amt_data_lake/parquet/amt/equity/student_history_dim/main.py
- Improve Parquet Files - Equity Collection
=> [BIA-1306] Improve Parquet Files - Equity Collection

src/edfi_amt_data_lake/parquet/amt/rls/rls_staff_classification_descriptor_scope_list/main.py, src/edfi_amt_data_lake/parquet/amt/rls/rls_student_data_authorization/main.py, src/edfi_amt_data_lake/parquet/amt/rls/rls_user_authorization/main.py, src/edfi_amt_data_lake/parquet/amt/rls/rls_user_dim/main.py
- Improve Parquet Files - RLS Collection
=> [BIA-1308] Improve Parquet Files - RLS Collection

src/edfi_amt_data_lake/parquet/amt/ews/student_early_warning_fact/main.py, src/edfi_amt_data_lake/parquet/amt/ews/student_section_grade_fact/main.py
- Improve Parquet Files - Ews Collection
=> [BIA-1307] Improve Parquet Files - Ews Collection

src/edfi_amt_data_lake/parquet/amt/epp/candidate_dim/main.py, src/edfi_amt_data_lake/parquet/amt/epp/candidate_survey_dim/main.py, src/edfi_amt_data_lake/parquet/amt/epp/epp_dim/main.py, src/edfi_amt_data_lake/parquet/amt/epp/epp_financial_aid_fact/main.py, src/edfi_amt_data_lake/parquet/amt/epp/evaluation_element_rating_dim/main.py, src/edfi_amt_data_lake/parquet/amt/epp/race_descriptor_dim/main.py, src/edfi_amt_data_lake/parquet/amt/epp/sex_descriptor_dim/main.py, src/edfi_amt_data_lake/parquet/amt/epp/term_descriptor_dim/main.py
- Improve Parquet Files - Epp Collection
=> BIA-1311 Improve Parquet Files - Epp Collection

src/edfi_amt_data_lake/parquet/amt/base/academic_time_period_dim/main.py, src/edfi_amt_data_lake/parquet/amt/base/all_student_school_dim/main.py, src/edfi_amt_data_lake/parquet/amt/base/base_collection.py, src/edfi_amt_data_lake/parquet/amt/base/class_period_dim/main.py, src/edfi_amt_data_lake/parquet/amt/base/contact_person_dim/main.py, src/edfi_amt_data_lake/parquet/amt/base/date_dim/main.py, src/edfi_amt_data_lake/parquet/amt/base/local_education_agency_dim/main.py, src/edfi_amt_data_lake/parquet/amt/base/school_dim/main.py, src/edfi_amt_data_lake/parquet/amt/base/section_dim/main.py, src/edfi_amt_data_lake/parquet/amt/base/staff_section_dim/main.py, src/edfi_amt_data_lake/parquet/amt/base/student_local_education_agency_dim/main.py, src/edfi_amt_data_lake/parquet/amt/base/student_program_dim/main.py, src/edfi_amt_data_lake/parquet/amt/base/student_school_dim/main.py
-  Improve Parquet Files - Base Collection
=> [BIA-1304] Improve Parquet Files - Base Collection

src/edfi_amt_data_lake/parquet/Common/pandasWrapper.py
Update pandasWrapper to change param errors to raise an exception instead of ignore it.
=> [BIA-1309] Update wrapper to_datetime exceptions

src/edfi_amt_data_lake/parquet/amt/rls/rls_staff_classification_descriptor_scope_list/main.py
- Consider optional data - rls_StaffClassificationDescriptorScopeList
=> [BIA-1275] Consider optional data - rls_StaffClassificationDescriptorScopeList

README.md
- Update folder path.
- Update Windows section.
=> [BIA-1292] Update readme instructions API-to-AMT-Data-Lake

src/edfi_amt_data_lake/helper/endpoint/endpoint.json, src/edfi_amt_data_lake/parquet/amt/asmt/assessment_fact/main.py
- Fix MaxScore column value error.
- Update AssessedGradeLevel to show descriptor description instead of code value.
=> [BIA-1327] API-To-AMT Update AssessmentFact with API 6.1

src/edfi_amt_data_lake/parquet/amt/base/contact_person_dim/main.py, src/edfi_amt_data_lake/parquet/amt/ews/student_section_grade_fact/main.py
- Fix problem in contact_person_dim.
- Add descriptorId to GradingPeriodKey
=> [BIA-1333] Update StudentSectionGradeFact to run the API-To-AMT against API 6.1

src/edfi_amt_data_lake/parquet/amt/equity/student_history_dim/main.py
- Update attendance rate formula.
=> [BIA-1332] Update StudentHistoryDim to be able to run the API-To-AMT against API 6.1
